### ISSUE TITLE
新註冊的會員第一次下拉選擇鄉鎮市後，不會出現對應的運送模式

### ISSUE THREAD

**Issue by enyilio** [RicherYang/RY-WC-City-Select#1]
設定條件:
1.設定運送區域在不同地區，顯示不同運送方式
2. 新註冊會員，第一次下拉選擇縣市及鄉鎮市欄位後，運送方式並沒有出現，除非再選一次鄉鎮市才會出現運送方式，或者直接手動輸入郵遞區號也會出現。

![20191213_033156](https://user-images.githubusercontent.com/9295447/70743132-12ecea80-1d5a-11ea-9022-7a2908324d9b.gif)

**Comment by RicherYang** [comment]
@enyilio  初步研究，這是 WooCommerce 本身的問題。

主因是我嘗試移除鄉鎮市連動的部分，只保留原生就有的縣市連動功能。
發現還是會有相同的狀態發生。

**Comment by linonedollar** [comment]
@enyilio 
你的國別選項欄位，看看能不能把它保留住?
我目前這種狀況是在於國別欄位，雖然你把它不啟用了，但是他運送方式判斷地區還是會去判斷那個空值
或者是在設定欄位那邊設定，預先載入顧客定位
