### ISSUE TITLE
Files of all the states and cities of the world.

### ISSUE THREAD

**Issue by sergioxdev** [RicherYang/RY-WC-City-Select#3]
I attach the files of all the states and cities of the world.

I hope it can help

https://github.com/sergioxdev/RY-WC-City-Select-cities-files

Sergio

**Comment by saaddouh** [comment]
hello sir where should i place these? and thank you so much

**Comment by sergioxdev** [comment]
Hi @saaddouh 

I added in the readme file,
how to add and update files.

**Comment by saaddouh** [comment]
thank you so much you saved my life

**Comment by RicherYang** [comment]
@saaddouh 
You can update to RY WC City Select version 1.0.8
use `add_filter('ry_wei_load_geonames_org', '__return_true');` to enable
