### ISSUE TITLE
感謝無私分享優良插件，想請問是否能幫助排解使用上碰到的問題？十分樂於贊助回饋創作，謝謝！

### ISSUE THREAD

**Issue by themcocom** [RicherYang/RY-WC-City-Select#4]
在使用後面臨幾個問題：

1.使用插件時無法調整下拉式選單的語言（敝司主要專攻台灣電商市場，希望能跳出來的語言是隨Translatepress正在的語言去跑；若不能則希望為預設中文，是否有任何地方能調整設定？）

2.於結帳頁面使用插件下拉選單選擇完縣市以後，後方的區會自動鎖死變成手動輸入（若直接選區域則不會碰到此Bug），這部分除了啟用插件外並沒有動任何設定，也沒辦法去做調整。

3.不論輸入的城市以及區域為何，都不會自動去抓郵遞區號，但是若使用的地方是在個人檔案 > 編輯地址 > 下拉選單則正常運作（不論是城市選擇之後的鄉鎮區選擇亦或郵遞區號都會正常運作）

期待能收到您的回覆或疑難排解的方式，感謝您的閱覽。

Best,
Mark.

[https://www.loom.com/share/fa4038bbcf3b47bd95620afc55445df2](url)

**Comment by RicherYang** [comment]
所有介面上看到的文字，都是符合 WordPress 國際化的相關規範，請自行依照 WordPress 的本地化規範製作你想要的特定國家/地區的語言，並此用相關的方式進行語言切換即可得到結果。

我使用經驗上可能發生的情況是因為佈景主題針對結帳頁面進行過客製化設計，導致 js 在偵測欄位改寫內容的時候發生錯誤。
本外掛開發時只針對 [Storefront](https://tw.wordpress.org/themes/storefront/) 佈景主題進行確認，也只提供 WordPress.org 上面的佈景主題的相容性修正 ( 全新安裝無任何客製化調整的情況 )
