### ISSUE TITLE
Invalid numeric literal

### ISSUE THREAD

**Issue by condor2** [RicherYang/RY-WC-City-Select#5]
If you use post code like this one **087005** plugin crash.

So this type of post codes should be added like this
**'087005'**

You can add this info on Readme

**Comment by RicherYang** [comment]
thank report issuu.
I had change the Example on Readme to use STRING type.

**Comment by condor2** [comment]
Another problem is when update.
The plugin should not delete files.

If you have files in cities on the next update all cities files will be deleted.

**Comment by RicherYang** [comment]
@condor2 This can't be fixed.
Because thw WordPress core to update the plugin, is delete all the file in plugin dir and unzip new version to dir.

**Comment by condor2** [comment]
OK.

Another small issue.

If you select a city who has postal code then you chose another with no postal code, the postal code field should be cleared and not to show postal code from prevision city
